### PR TITLE
Add defaults and fix reference bug

### PR DESCRIPTION
**Pull request by shagra-ms**
Changes in the update -
1. Fixed reference bug in column-formatting schema that showed an [error in VS2019](https://developercommunity.visualstudio.com/t/Issue-with-SharePoint-JSON-Schema-in-Vis/1503628)
2. Added some defaults for improved authoring experience

### CODE REVIEW

**Comment by shagra-ms** [comment]
@octogonz Can you please help by merging this?

**Comment by shagra-ms** [comment]
@asnow003 Can you please help by merging this?

**Comment by shagra-ms** [comment]
@microsoft/json-schemas-admins Can someone please help by merging this ?

**Review by lindalu-MSFT — APPROVED** [review]

**Comment by lindalu-MSFT** [comment]
Reviewed and merged, next time @ me and I'll hop on it sooner! Thanks, Linda

**Pull request merged**
