### PR TITLE
Added defaultHoverField and customCardProps

### PR DESCRIPTION
**Pull request by shagra-ms**
Updated schema with new features.

### CODE REVIEW

**Comment by shagra-ms** [comment]
@VesaJuvonen Please approve if this looks good to you.

**Comment by octogonz** [comment]
@shagra-ms Are you asking for an application specific review of the schema content?

If you just want an approval to add this update, I can merge+publish it for you.

**Comment by shagra-ms** [comment]
That will help @octogonz. Thanks!

**Comment by octogonz** [comment]
Merged and pushed to the `live` branch

**Pull request merged**
